// Core ingredient-level inventory
export const MOCK_INGREDIENTS = [
  { id: 1, name: 'Basmati Rice', unit: 'kg', stock: 100, minStock: 10, reorderLeadDays: 3, unitCost: 2.5 },
  { id: 2, name: 'Chicken', unit: 'kg', stock: 60, minStock: 8, reorderLeadDays: 2, unitCost: 5.2 },
  { id: 3, name: 'Mutton', unit: 'kg', stock: 40, minStock: 6, reorderLeadDays: 3, unitCost: 8.5 },
  { id: 4, name: 'Shrimp', unit: 'kg', stock: 25, minStock: 5, reorderLeadDays: 4, unitCost: 9.0 },
  { id: 5, name: 'Paneer', unit: 'kg', stock: 30, minStock: 5, reorderLeadDays: 3, unitCost: 4.5 },
  { id: 6, name: 'Vegetables', unit: 'kg', stock: 80, minStock: 12, reorderLeadDays: 2, unitCost: 3.2 },
  { id: 7, name: 'Eggs', unit: 'units', stock: 120, minStock: 20, reorderLeadDays: 2, unitCost: 0.2 },
  { id: 8, name: 'Flour', unit: 'kg', stock: 60, minStock: 8, reorderLeadDays: 2, unitCost: 1.1 },
  { id: 9, name: 'Dairy', unit: 'kg', stock: 70, minStock: 10, reorderLeadDays: 2, unitCost: 3.8 },
  { id: 10, name: 'Spices', unit: 'kg', stock: 40, minStock: 5, reorderLeadDays: 2, unitCost: 10.0 },
];

export const MENU_RECIPES = {
  1: [
    { ingredientId: 1, qty: 0.45 },
    { ingredientId: 2, qty: 0.22 },
    { ingredientId: 9, qty: 0.08 },
    { ingredientId: 10, qty: 0.02 },
  ],
  2: [
    { ingredientId: 1, qty: 0.45 },
    { ingredientId: 3, qty: 0.26 },
    { ingredientId: 9, qty: 0.08 },
    { ingredientId: 10, qty: 0.02 },
  ],
  3: [
    { ingredientId: 1, qty: 0.42 },
    { ingredientId: 4, qty: 0.3 },
    { ingredientId: 9, qty: 0.06 },
    { ingredientId: 10, qty: 0.02 },
  ],
  4: [
    { ingredientId: 1, qty: 0.4 },
    { ingredientId: 6, qty: 0.3 },
    { ingredientId: 9, qty: 0.05 },
    { ingredientId: 10, qty: 0.02 },
  ],
  5: [
    { ingredientId: 1, qty: 0.4 },
    { ingredientId: 7, qty: 2 },
    { ingredientId: 9, qty: 0.05 },
    { ingredientId: 10, qty: 0.02 },
  ],
  6: [{ ingredientId: 2, qty: 0.18 }, { ingredientId: 10, qty: 0.03 }, { ingredientId: 9, qty: 0.04 }],
  7: [{ ingredientId: 5, qty: 0.2 }, { ingredientId: 10, qty: 0.03 }, { ingredientId: 9, qty: 0.04 }],
  8: [{ ingredientId: 3, qty: 0.16 }, { ingredientId: 10, qty: 0.03 }, { ingredientId: 9, qty: 0.04 }],
  // ... more recipes assumed mapping to menu items
};

export const MOCK_MENU = [
  {
    id: 1,
    name: 'Chicken Dum Biryani',
    price: 18.99,
    category: 'Biryani',
    image: '🍚',
    prep_time: 25,
    rating: 4.8,
    spiceLevel: 3,
    isVeg: false,
    isHalal: true,
    desc: 'Traditional Hyderabadi dum biryani with succulent chicken and aromatic basmati rice.',
  },
  {
    id: 2,
    name: 'Mutton Dum Biryani',
    price: 22.99,
    category: 'Biryani',
    image: 'muttonBiryani',
    prep_time: 30,
    rating: 4.9,
    spiceLevel: 3,
    isVeg: false,
    isHalal: true,
    desc: 'Slow-cooked mutton layered with saffron-infused rice and premium heritage spices.',
  },
  {
    id: 3,
    name: 'Shrimp Biryani',
    price: 24.99,
    category: 'Biryani',
    image: 'heroBiryani',
    prep_time: 20,
    rating: 4.7,
    spiceLevel: 2,
    isVeg: false,
    isHalal: true,
    desc: 'Succulent gulf shrimp marinated in a zesty masala and layered with fragrant rice.',
  },
  {
    id: 4,
    name: 'Vegetable Dum Biryani',
    price: 16.99,
    category: 'Biryani',
    image: 'heroBiryani',
    prep_time: 22,
    rating: 4.6,
    spiceLevel: 2,
    isVeg: true,
    isHalal: true,
    desc: 'A garden-fresh blend of seasonal vegetables cooked with aromatic long-grain basmati.',
  },
  {
    id: 5,
    name: 'Egg Biryani',
    price: 17.99,
    category: 'Biryani',
    image: 'heroBiryani',
    prep_time: 20,
    rating: 4.5,
    spiceLevel: 2,
    isVeg: false,
    isHalal: true,
    desc: 'Hard-boiled eggs tossed in a spicy masala and layered with saffron-flavored rice.',
  },
  // Add more items if needed to match the full 25 items
  {
    id: 6,
    name: 'Chicken Tikka',
    price: 14.99,
    category: 'Appetizers',
    image: 'chickenTikka',
    prep_time: 15,
    rating: 4.7,
    spiceLevel: 2,
    isVeg: false,
    isHalal: true,
    desc: 'Boneless chicken chunks marinated in yogurt and spices, grilled to smoky perfection.',
  },
  {
    id: 7,
    name: 'Paneer 65',
    price: 12.99,
    category: 'Appetizers',
    image: 'chickenTikka',
    prep_time: 12,
    rating: 4.6,
    spiceLevel: 3,
    isVeg: true,
    isHalal: true,
    desc: 'Crispy fried paneer cubes tossed in a spicy, tangy South Indian tempered sauce.',
  },
  {
    id: 8,
    name: 'Lamb Seekh Kabab',
    price: 15.99,
    category: 'Appetizers',
    image: 'chickenTikka',
    prep_time: 15,
    rating: 4.8,
    spiceLevel: 2,
    isVeg: false,
    isHalal: true,
    desc: 'Minced lamb blended with herbs and specialty spices, skewered and tandoor-roasted.',
  },
  {
    id: 9,
    name: 'Chicken Lollipop',
    price: 13.99,
    category: 'Appetizers',
    image: 'chickenTikka',
    prep_time: 12,
    rating: 4.5,
    spiceLevel: 2,
    isVeg: false,
    isHalal: true,
    desc: 'Crisp chicken wings Frenched and tossed in a zesty Indo-Chinese fusion sauce.',
  },
  {
    id: 10,
    name: 'Samosa (3pc)',
    price: 8.99,
    category: 'Appetizers',
    image: 'chickenTikka',
    prep_time: 8,
    rating: 4.4,
    spiceLevel: 1,
    isVeg: true,
    isHalal: true,
    desc: 'Hand-crafted pastry shells filled with spiced potatoes, peas, and artisan herbs.',
  },
  {
    id: 11,
    name: 'Garlic Naan',
    price: 4.99,
    category: 'Breads',
    image: 'heroBiryani',
    prep_time: 5,
    rating: 4.7,
    spiceLevel: 1,
    isVeg: true,
    isHalal: true,
    desc: 'Freshly baked leavened bread topped with minced garlic and artisanal butter.',
  },
  {
    id: 12,
    name: 'Butter Naan',
    price: 3.99,
    category: 'Breads',
    image: 'heroBiryani',
    prep_time: 5,
    rating: 4.6,
    spiceLevel: 0,
    isVeg: true,
    isHalal: true,
    desc: 'Classic soft tandoor-baked bread glazed with premium melted butter.',
  },
  {
    id: 13,
    name: 'Roti',
    price: 2.99,
    category: 'Breads',
    image: 'heroBiryani',
    prep_time: 3,
    rating: 4.5,
    spiceLevel: 0,
    isVeg: true,
    isHalal: true,
    desc: 'Simple whole wheat flatbread baked in our traditional clay oven.',
  },
  {
    id: 14,
    name: 'Kulcha (Cheese)',
    price: 5.99,
    category: 'Breads',
    image: 'heroBiryani',
    prep_time: 8,
    rating: 4.8,
    spiceLevel: 1,
    isVeg: true,
    isHalal: true,
    desc: 'Stuffed bread filled with a blend of cheeses and mild spices.',
  },
  {
    id: 15,
    name: 'Butter Chicken',
    price: 16.99,
    category: 'Curries',
    image: 'chickenTikka',
    prep_time: 20,
    rating: 4.9,
    spiceLevel: 1,
    isVeg: false,
    isHalal: true,
    desc: 'Tender tandoori chicken simmered in a rich, creamy tomato and cashew sauce.',
  },
  {
    id: 16,
    name: 'Paneer Tikka Masala',
    price: 14.99,
    category: 'Curries',
    image: 'chickenTikka',
    prep_time: 18,
    rating: 4.8,
    spiceLevel: 2,
    isVeg: true,
    isHalal: true,
    desc: 'Grilled paneer cubes cooked in a vibrant, spiced onion and tomato gravy.',
  },
  {
    id: 17,
    name: 'Lamb Rogan Josh',
    price: 18.99,
    category: 'Curries',
    image: 'chickenTikka',
    prep_time: 25,
    rating: 4.7,
    spiceLevel: 3,
    isVeg: false,
    isHalal: true,
    desc: 'Classic Kashmiri lamb curry slow-cooked with ginger, garlic, and specialty spices.',
  },
  {
    id: 18,
    name: 'Chole Bhature',
    price: 9.99,
    category: 'Curries',
    image: 'chickenTikka',
    prep_time: 15,
    rating: 4.6,
    spiceLevel: 2,
    isVeg: true,
    isHalal: true,
    desc: 'Spiced chickpea curry served with a large, fluffy deep-fried leavened bread.',
  },
  {
    id: 19,
    name: 'Rasmalai',
    price: 5.99,
    category: 'Dessert',
    image: 'rasmalai',
    prep_time: 2,
    rating: 4.8,
    spiceLevel: 0,
    isVeg: true,
    isHalal: true,
    desc: 'Delicate cheese patties soaked in saffron-flavored sweetened milk.',
  },
  {
    id: 20,
    name: 'Gulab Jamun',
    price: 5.99,
    category: 'Dessert',
    image: 'rasmalai',
    prep_time: 2,
    rating: 4.7,
    spiceLevel: 0,
    isVeg: true,
    isHalal: true,
    desc: 'Traditional milk-solid dumplings fried and soaked in cardamom sugar syrup.',
  },
  {
    id: 21,
    name: 'Kheer',
    price: 6.99,
    category: 'Dessert',
    image: 'rasmalai',
    prep_time: 2,
    rating: 4.6,
    spiceLevel: 0,
    isVeg: true,
    isHalal: true,
    desc: 'Classic slow-cooked rice pudding infused with nuts and fragrant cardamom.',
  },
  {
    id: 22,
    name: 'Ice Cream Kulfi',
    price: 4.99,
    category: 'Dessert',
    image: 'rasmalai',
    prep_time: 1,
    rating: 4.9,
    spiceLevel: 0,
    isVeg: true,
    isHalal: true,
    desc: 'Traditional dense Indian ice cream with pistachio and saffron flavors.',
  },
  {
    id: 23,
    name: 'Family Combo (4)',
    price: 49.99,
    category: 'Combos',
    image: 'muttonBiryani',
    prep_time: 30,
    rating: 4.9,
    spiceLevel: 3,
    isVeg: false,
    isHalal: true,
    desc: 'The ultimate spread: 2 Large Biryanis, 2 Appetizers, and 4 Desserts.',
  },
  {
    id: 24,
    name: 'Couple Combo (2)',
    price: 35.99,
    category: 'Combos',
    image: 'heroBiryani',
    prep_time: 25,
    rating: 4.8,
    spiceLevel: 2,
    isVeg: false,
    isHalal: true,
    desc: 'Perfect for two: 1 Large Biryani, 1 Appetizer, and 2 Soft Drinks.',
  },
  {
    id: 25,
    name: 'Party Pack (6)',
    price: 79.99,
    category: 'Combos',
    image: 'muttonBiryani',
    prep_time: 35,
    rating: 4.9,
    spiceLevel: 3,
    isVeg: false,
    isHalal: true,
    desc: 'Mega feast: 3 Large Biryanis, 3 Appetizers, and Family Sized Desserts.',
  },
];

export const MOCK_ORDERS = [
  {
    id: 'ORD_001',
    items: [{ id: 1, name: 'Chicken Dum Biryani', price: 18.99, quantity: 2 }, { id: 6, name: 'Chicken Tikka', price: 14.99, quantity: 1 }],
    total: 52.97,
    table: 'T1',
    captain: 'Arjun Singh',
    status: 'pending',
    timestamp: new Date(Date.now() - 5 * 60000).toISOString(),
    rating: 0,
  },
  {
    id: 'ORD_002',
    items: [{ id: 2, name: 'Mutton Dum Biryani', price: 22.99, quantity: 1 }],
    total: 22.99,
    table: 'T2',
    captain: 'Arjun Singh',
    status: 'preparing',
    timestamp: new Date(Date.now() - 10 * 60000).toISOString(),
    rating: 0,
  },
  {
    id: 'ORD_003',
    items: [{ id: 23, name: 'Family Combo (4)', price: 49.99, quantity: 1 }],
    total: 49.99,
    table: 'T3',
    captain: 'Arjun Singh',
    status: 'served',
    timestamp: new Date(Date.now() - 35 * 60000).toISOString(),
    rating: 5,
    feedback: 'Excellent taste!',
  },
];

export const MOCK_RESERVATIONS = [
  { id: 'RES_001', customerName: 'Raj Patel', email: 'raj@example.com', phone: '+1-555-1001', date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0], time: '19:00', guests: 4, notes: 'Birthday celebration', status: 'confirmed', tableAssigned: 'T5', createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'RES_002', customerName: 'Priya Singh', email: 'priya@example.com', phone: '+1-555-1002', date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0], time: '18:30', guests: 6, notes: 'Anniversary dinner', status: 'confirmed', tableAssigned: 'T6', createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'RES_003', customerName: 'Amit Kumar', email: 'amit@example.com', phone: '+1-555-1003', date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0], time: '20:00', guests: 2, notes: 'Date night', status: 'pending', tableAssigned: null, createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString() },
];

export const MOCK_CATERING_ORDERS = [
  { id: 'CATER_001', customerName: 'Corporate Events Inc', email: 'corporate@example.com', phone: '+1-555-2001', eventType: 'Corporate Lunch', eventDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0], guestCount: 50, menu: ['Chicken Dum Biryani', 'Paneer Tikka Masala', 'Garlic Naan', 'Gulab Jamun'], venue: '456 Business Park, NYC', budget: 1500, status: 'confirmed', totalPrice: 1495, deliveryTime: '12:00', notes: 'Vegetarian options needed', createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString() },
];

export const MOCK_GIFT_CARDS = [
  { id: 'GC_001', code: 'BIRYANI50ABC123', denomination: 50, balance: 50, createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(), expiryDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString().split('T')[0], purchasedBy: 'John Doe', purchasedFor: 'Gift', status: 'active', transactionHistory: [] },
];

export const MOCK_DELIVERIES = [
  { id: 'DEL_001', orderId: 'ORD_101', customerName: 'Sarah Williams', phone: '+1-555-3001', address: '789 Park Avenue, NYC', items: ['Chicken Dum Biryani x2', 'Garlic Naan x2', 'Rasmalai x1'], totalAmount: 67.96, status: 'in-transit', assignedDriver: 'Vikram Patel', driverPhone: '+1-555-0104', driverRating: 4.8, estimatedDelivery: '45 mins', currentLocation: 'Manhattan, NY', orderPlacedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(), deliveryStartedAt: new Date(Date.now() - 8 * 60 * 1000).toISOString() },
];

export const MOCK_ORDER_HISTORY = [
  { id: 'CUST_ORD_001', orderNumber: 'ORD_201', date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), items: ['Chicken Dum Biryani x2', 'Garlic Naan x2'], total: 47.96, status: 'completed', rating: 5, feedback: 'Excellent!' },
];

export const MOCK_CART_ITEMS = [
  { id: 1, name: 'Chicken Dum Biryani', price: 18.99, quantity: 1, category: 'Biryani' },
  { id: 6, name: 'Chicken Tikka', price: 14.99, quantity: 1, category: 'Appetizers' },
];
